/**
 * Scan small_paths/ and write src/UltraSmallPathsIndex.js
 * Index shape: { [walls]: { paths: { [file]: lineCount }, cycles: { ... } } }
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const SRC = path.join(ROOT, "small_paths");
const DEST = path.join(ROOT, "src", "UltraSmallPathsIndex.js");
const BASE_URL =
  "https://raw.githubusercontent.com/DarkSnakeGang/GoogleSnakeRemix/main/small_paths/";

function countNonEmptyLines(filePath) {
  const buf = fs.readFileSync(filePath);
  let count = 0;
  let start = 0;
  for (let i = 0; i < buf.length; i++) {
    if (buf[i] === 0x0a) {
      const end = i > start && buf[i - 1] === 0x0d ? i - 1 : i;
      if (end > start) count++;
      start = i + 1;
    }
  }
  if (start < buf.length) count++;
  return count;
}

function listTxtFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((n) => /^\d+\.txt$/i.test(n))
    .map((n) => ({
      id: String(parseInt(n, 10)),
      name: n,
      full: path.join(dir, n),
    }))
    .sort((a, b) => parseInt(a.id, 10) - parseInt(b.id, 10));
}

function scanKind(wallDir, kind) {
  const kindDir = path.join(wallDir, kind);
  const out = {};
  for (const f of listTxtFiles(kindDir)) {
    out[f.id] = countNonEmptyLines(f.full);
  }
  return out;
}

if (!fs.existsSync(SRC)) {
  console.error("missing", SRC);
  process.exit(1);
}

const index = {};
const walls = fs
  .readdirSync(SRC)
  .filter((n) => /^\d+$/.test(n))
  .sort((a, b) => parseInt(a, 10) - parseInt(b, 10));

for (const w of walls) {
  const wallDir = path.join(SRC, w);
  if (!fs.statSync(wallDir).isDirectory()) continue;
  const paths = scanKind(wallDir, "paths");
  const cycles = scanKind(wallDir, "cycles");
  if (!Object.keys(paths).length && !Object.keys(cycles).length) continue;
  index[w] = { paths, cycles };
  const pFiles = Object.keys(paths).length;
  const cFiles = Object.keys(cycles).length;
  console.error(
    `walls=${w} pathsFiles=${pFiles} cyclesFiles=${cFiles}`
  );
}

const body =
  "/* Generated by tools/build_small_paths_index.mjs — do not edit by hand. */\n" +
  "window.ULTRA_SMALL_PATHS_INDEX = " +
  JSON.stringify(index) +
  ";\n" +
  "window.ULTRA_SMALL_PATHS_BASE = " +
  JSON.stringify(BASE_URL) +
  ";\n";

fs.writeFileSync(DEST, body);
console.error("wrote", DEST, body.length, "bytes");
